---
- hosts: all
  become: true
  become_method: sudo

  vars:
    name: webhook-to-fedora-messaging
    pkg_name: webhook_to_fedora_messaging
    ipa_admin_user: admin
    ipa_admin_password: password
    krb_realm: TINYSTAGE.TEST

  roles:
    - core
    # If you need Tinystage:
    # - ipa-client
    # If you need a TLS cert from Tinystage:
    # - cert
    - dev
