---
- hosts: all
  become: true
  become_method: sudo

  vars:
    app_name: webhook-to-fedora-messaging
    pkg_name: webhook_to_fedora_messaging
    ipa_admin_user: admin
    ipa_admin_password: password
    krb_realm: TINYSTAGE.TEST
    cert_owner: vagrant

  roles:
    - common
    - ipa-client
    - cert
    - gss-proxy
    - dev
