---
- hosts: all
  become: true
  become_method: sudo

  vars:
    app_name: webhook-to-fedora-messaging
    pkg_name: webhook_to_fedora_messaging
    ipa_admin_user: admin
    ipa_admin_password: password
    krb_realm: TINYSTAGE.TEST
    cert_owner: vagrant

  roles:
    - common
    - ipa-client
    - cert
    - name: gss-proxy
      keytab_owner: vagrant
      keytab_group: vagrant
    - name: oidc-register
      redirect_url: https://{{ ansible_fqdn }}/docs/oauth2-redirect
      public_client: true
      dest: /home/vagrant/frontend_oidc.json
    - dev
