amqp_url = "localhost"
callback = ""
passive_declares = false
publish_exchange = "amq.topic"
topic_prefix = ""
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"
ca_cert = "/etc/fedora-messaging/cacert.pem"
[[bindings]]
queue = "my_queue"
exchange = "amq.topic"
routing_keys = [ "#",]

[tls]
ca_cert = ""
keyfile = ""
certfile = ""

[client_properties]
app = "webhook2fedmsg"

[consumer_config]
example_key = "for my consumer"

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false

[queues.my_queue]
durable = true
auto_delete = false
exclusive = false

[log_config.root]
level = "ERROR"
handlers = [ "console",]

[exchanges."amq.topic".arguments]

[queues.my_queue.arguments]

[log_config.formatters.simple]
format = "[%(levelname)s %(name)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = [ "console",]

[log_config.loggers.twisted]
level = "INFO"
propagate = false
handlers = [ "console",]

[log_config.loggers.pika]
level = "WARNING"
propagate = false
handlers = [ "console",]
