[flaskapp]
DEBUG = true
SECRET_KEY = "vagrant-env"
FASJSON_URL = "https://fasjson.tinystage.test/fasjson"
SQLALCHEMY_DATABASE_URI = "sqlite:////home/vagrant/w2fm.db"

  [flaskapp.logsconf]
  version = 1
  disable_existing_loggers = false

    [flaskapp.logsconf.handlers]

      [flaskapp.logsconf.handlers.wsgi]
      class = "logging.StreamHandler"
      stream = "ext://flask.logging.wsgi_errors_stream"
      level = "INFO"
      formatter = "default"

    [flaskapp.logsconf.formatters]

      [flaskapp.logsconf.formatters.default]
      format = "[W2FM] %(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt = "[%Y-%m-%d %I:%M:%S %z]"

    [flaskapp.logsconf.root]
    handlers = ["wsgi"]
    level = "INFO"

    [flaskapp.logsconf.loggers]

      [flaskapp.logsconf.loggers.werkzeug]
      handlers = ["wsgi"]
      level = "INFO"
      propagate = false
